Repository bitRocket-dev/.github, pull requests merged in 2022-10, with the labels that each got.

#4 Aggiunte Icone
  .DS_Store
  profile/ABOUT.md
  profile/CASE_HISTORIES.md
  profile/MANIFEST.md
  profile/WHY_BITROCKET-DEV.md
Labels: PULL REQUEST

#10 Added icons in Readme
  .DS_Store
  assets/.DS_Store
  profile/README.md
Labels: PULL REQUEST

#59 Aggiunti alle pagine Readme e Case Histories i clienti DoveVivo e Iungo.
  assets/clients/dovevivo_logo.png
  assets/clients/iungo_logo.png
  pages/CASE_HISTORY.md
  profile/README.md
Labels: FEAT

#55 docs: fix/dev-tab
  profile/README.md
Labels: DOC

#62 Added philip morris to case history ad readme
  assets/clients/philipmorris_logo.png
  pages/CASE_HISTORY.md
  pages/CASE_HISTORY.md~Stashed changes
  profile/README.md
Labels: FEAT

#69 Corretto posizionamento immagini clienti in Readme
  assets/clients/philipmorris_logo.png
  profile/README.md
Labels: BUG
